import 'package:flutter/material.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

import '../../../data/reports_api.dart';
import '../../../theme/app_colors.dart';
import '../timeline_event.dart';
import 'activity_timeline.dart' show formatDateTimeIN;

enum ReportSortKey { name, format, generatedAt, size }

class ReportsSort {
  const ReportsSort(this.key, this.ascending);
  final ReportSortKey key;
  final bool ascending;
}

/// Direct port of History.tsx's "Reports Export Archive" section: a
/// sortable, paginated table of every generated report.
class ReportsArchiveTable extends StatelessWidget {
  const ReportsArchiveTable({
    super.key,
    required this.paginatedReports,
    required this.totalFiltered,
    required this.sort,
    required this.onSortChanged,
    required this.currentPage,
    required this.totalPages,
    required this.itemsPerPage,
    required this.onPageChanged,
    required this.onDownload,
    required this.onView,
    required this.onDelete,
    required this.isLoading,
  });

  final List<ReportRecord> paginatedReports;
  final int totalFiltered;
  final ReportsSort sort;
  final ValueChanged<ReportSortKey> onSortChanged;
  final int currentPage;
  final int totalPages;
  final int itemsPerPage;
  final ValueChanged<int> onPageChanged;
  final ValueChanged<ReportRecord> onDownload;
  final ValueChanged<ReportRecord> onView;
  final ValueChanged<ReportRecord> onDelete;
  final bool isLoading;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: AppColors.cardBg,
        border: Border.all(color: AppColors.cardBorder),
        borderRadius: BorderRadius.circular(16),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Row(
            children: [
              const Icon(LucideIcons.fileSpreadsheet, size: 18, color: AppColors.accentBlue),
              const SizedBox(width: 8),
              const Expanded(child: Text('Reports Export Archive', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700))),
              Text('$totalFiltered total report logs', style: const TextStyle(fontSize: 11, color: AppColors.secondaryText)),
            ],
          ),
          const SizedBox(height: 16),
          if (isLoading)
            const Padding(
              padding: EdgeInsets.symmetric(vertical: 24),
              child: Center(child: Text('Syncing operational report indexes...', style: TextStyle(color: AppColors.secondaryText))),
            )
          else if (paginatedReports.isEmpty && totalFiltered == 0)
            const Padding(
              padding: EdgeInsets.symmetric(vertical: 24),
              child: Center(child: Text('No reports generated or found matching search parameters.', style: TextStyle(color: AppColors.secondaryText))),
            )
          else ...[
            SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: DataTable(
                headingRowHeight: 38,
                dataRowMinHeight: 44,
                dataRowMaxHeight: 52,
                columnSpacing: 20,
                columns: [
                  _sortableColumn('Report Name', ReportSortKey.name),
                  _sortableColumn('Format', ReportSortKey.format),
                  const DataColumn(label: Text('Generated By')),
                  _sortableColumn('Created Time', ReportSortKey.generatedAt),
                  const DataColumn(label: Text('Status')),
                  _sortableColumn('Size', ReportSortKey.size),
                  const DataColumn(label: Text('Actions')),
                ],
                rows: [for (final r in paginatedReports) _row(r)],
              ),
            ),
            if (totalPages > 1) ...[
              const SizedBox(height: 14),
              Row(
                children: [
                  Expanded(
                    child: Text(
                      'Showing ${((currentPage - 1) * itemsPerPage) + 1} to ${(currentPage * itemsPerPage).clamp(0, totalFiltered)} of $totalFiltered reports',
                      style: const TextStyle(fontSize: 11, color: AppColors.secondaryText),
                    ),
                  ),
                  IconButton(onPressed: currentPage == 1 ? null : () => onPageChanged(currentPage - 1), icon: const Icon(LucideIcons.chevronLeft, size: 16)),
                  for (var p = 1; p <= totalPages; p++)
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 2),
                      child: InkWell(
                        onTap: () => onPageChanged(p),
                        borderRadius: BorderRadius.circular(6),
                        child: Container(
                          width: 28,
                          height: 28,
                          alignment: Alignment.center,
                          decoration: BoxDecoration(
                            color: p == currentPage ? AppColors.accentBlue : Colors.transparent,
                            borderRadius: BorderRadius.circular(6),
                          ),
                          child: Text('$p', style: TextStyle(fontSize: 12, color: p == currentPage ? Colors.white : AppColors.primaryText)),
                        ),
                      ),
                    ),
                  IconButton(onPressed: currentPage == totalPages ? null : () => onPageChanged(currentPage + 1), icon: const Icon(LucideIcons.chevronRight, size: 16)),
                ],
              ),
            ],
          ],
        ],
      ),
    );
  }

  DataColumn _sortableColumn(String label, ReportSortKey key) {
    final active = sort.key == key;
    return DataColumn(
      label: InkWell(
        onTap: () => onSortChanged(key),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(label, style: const TextStyle(fontWeight: FontWeight.w600)),
            if (active) ...[
              const SizedBox(width: 4),
              Icon(sort.ascending ? LucideIcons.chevronUp : LucideIcons.chevronDown, size: 12),
            ],
          ],
        ),
      ),
    );
  }

  DataRow _row(ReportRecord r) {
    return DataRow(cells: [
      DataCell(Text(r.reportName, style: const TextStyle(fontFamily: 'monospace', fontSize: 12))),
      DataCell(Container(
        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
        decoration: BoxDecoration(color: AppColors.accentBlueLight, borderRadius: BorderRadius.circular(6)),
        child: Text(r.reportType, style: const TextStyle(fontSize: 10, fontWeight: FontWeight.w700, color: AppColors.accentBlue)),
      )),
      DataCell(Row(mainAxisSize: MainAxisSize.min, children: [
        const Icon(LucideIcons.userCheck, size: 12, color: AppColors.secondaryText),
        const SizedBox(width: 4),
        Text(reportUserFor(r.id), style: const TextStyle(fontSize: 12)),
      ])),
      DataCell(Text(formatDateTimeIN(DateTime.tryParse(r.generatedAt ?? r.createdAt) ?? DateTime.now()), style: const TextStyle(fontSize: 11, color: AppColors.secondaryText))),
      DataCell(Container(
        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
        decoration: BoxDecoration(color: AppColors.successLight, borderRadius: BorderRadius.circular(9999)),
        child: const Row(mainAxisSize: MainAxisSize.min, children: [
          Icon(LucideIcons.checkCircle2, size: 11, color: AppColors.success),
          SizedBox(width: 4),
          Text('Success', style: TextStyle(fontSize: 10, fontWeight: FontWeight.w700, color: AppColors.success)),
        ]),
      )),
      DataCell(Text(reportSizeFor(r.id), style: const TextStyle(fontFamily: 'monospace', fontSize: 11))),
      DataCell(Row(mainAxisSize: MainAxisSize.min, children: [
        IconButton(icon: const Icon(LucideIcons.download, size: 14), onPressed: () => onDownload(r), tooltip: 'Download document', constraints: const BoxConstraints(minWidth: 30, minHeight: 30), padding: EdgeInsets.zero),
        IconButton(icon: const Icon(LucideIcons.arrowUpRight, size: 14), onPressed: () => onView(r), tooltip: 'View PDF summary', constraints: const BoxConstraints(minWidth: 30, minHeight: 30), padding: EdgeInsets.zero),
        IconButton(icon: const Icon(LucideIcons.trash2, size: 14, color: AppColors.danger), onPressed: () => onDelete(r), tooltip: 'Delete report index record', constraints: const BoxConstraints(minWidth: 30, minHeight: 30), padding: EdgeInsets.zero),
      ])),
    ]);
  }
}
