"""add tracking_id

Revision ID: 3c5f2d8ebbf1
Revises: 5de4c308d694
Create Date: 2026-07-02 11:10:54.809309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c5f2d8ebbf1'
down_revision: Union[str, Sequence[str], None] = '5de4c308d694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('road_distresses', sa.Column('tracking_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('road_distresses', 'tracking_id')
    # ### end Alembic commands ###
