"""add tracking metadata columns

Revision ID: 6aa97bc187db
Revises: 3c5f2d8ebbf1
Create Date: 2026-07-02 11:18:52.477182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6aa97bc187db'
down_revision: Union[str, Sequence[str], None] = '3c5f2d8ebbf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('road_distresses', sa.Column('first_frame', sa.Integer(), nullable=True))
    op.add_column('road_distresses', sa.Column('last_frame', sa.Integer(), nullable=True))
    op.add_column('road_distresses', sa.Column('frames_visible', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('road_distresses', 'frames_visible')
    op.drop_column('road_distresses', 'last_frame')
    op.drop_column('road_distresses', 'first_frame')
    # ### end Alembic commands ###
